name: test

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        openrestyVersion: ["1.19.9.1"]
        buildCache: ["true", "false"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-openresty@main
      with:
        openrestyVersion: ${{ matrix.openrestyVersion }}
        buildCache: ${{ matrix.buildCache }}

    - name: test resty
      run: resty -e 'print("hi from lua")'

    - name: test opm
      run: opm --cwd install leafo/pgmoon
